backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
local_backend: true #allows you to mess with your cms locally
media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
editor:
  preview: false # we're going to hide the preview editor
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "heroImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "string", default: "../../layouts/BlogPost.astro"}